### ISSUE TITLE
Would be nice with an example with clojure lists and maps

### ISSUE THREAD

**Issue by mattiasw2** [Frege/frege-lein-plugin#12]
Just googling around, and it would be nice to see that also complex data can be sent from clojure to frege, and returned back. Part of this is how to make frege be sure about that they are correctly typed.

**Comment by seancorfield** [comment]
Sounds like a good idea but pressures of work have moved me away from Frege for quite a while so it's unlikely to happen soon.

In addition, we switched from Leiningen to Boot at work nearly a year ago now so _if_ I invest more time in Clojure/Frege interoperability, it's likely to be via a new Boot plugin instead, rather than expanding a Leiningen plugin we wouldn't be able to use.

I'd be perfectly happy to see a Pull Request for additional examples here tho'...

**Comment by mattiasw2** [comment]
Thanks, fully understand you!
